### ISSUE TITLE
Ensure we use only frozen Skia APIs

### ISSUE THREAD

**Issue by pavpanchekha** [browserengineering/book#1144]
Skia seems to somewhat-regularly change its API. In theory, some classes are annotated `SK_API`, which indicates that they are frozen, while others are not frozen. We should ideally use only frozen APIs. That said, even "frozen" APIs can change; for example, `SkPaint::getBlendMode` was replaced with `SkPaint::getBlendMode_or` recently.

Still, perhaps we can assume that the `SK_API` classes and methods will not change much, and that `skia-python` can maybe paper over changes if they do (as they did with `getBlendMode_or`). Then the question is: what else do we need to avoid using? I did an exhaustive audit of our source code and here's what I got:

Definitely needs changing:
 - [ ] Everything related to `FilterQuality`, namely its use in `Paint`, its use in `drawImageRect`, and then the actual values of that enum, were all removed way back, like in m90 or something.
 
Maybe will change in the future:
- [ ] `BlendMode` is a public enum but isn't `SK_API`. (I'm not even sure if enums _can_ be `SK_API` but in any case `BlendMode` seems to have the same status as `FilterQuality`.) The fact that `getBlendMode` changed doesn't make me feel better—looks like Skia is moving toward a new `Blender` abstraction.
- [ ] A lot of the GPU-related APIs are from the "legacy GL API" and so are on their way out. There's now I think a new GPU driver? Maybe using Vulkan? I found this code pretty confusing.

**Comment by chrishtr** [comment]
> * Am I correct that this changed in Skia? Do the original high/medium/low constants exist somewhere or do we need to do all the steps above to construct it?

Not sure, I'll check with the Skia team.

> * Does Skia regularly make breaking changes? Is there any way to avoid? (This is already the second, after they removed `getBlendMode` in favor of `getBlendMode_or`.

They do sometimes make breaking changes. Did the Skia Python module already update and break out app? It seems to work locally.

**Comment by pavpanchekha** [comment]
It's a little tricky. The Skia-Python module has not put out a new "official" release in a while, but the last "official" release doesn't work with Python 3.12 so I've been installing their "beta" releases and those track API changes, including the breaking ones.

**Comment by HinTak** [comment]
The SamplingOptions change is thr first item in the release note: https://github.com/kyamagu/skia-python/blob/main/relnotes/README.m116.md#general-overview-of-changes-between-m87-and-m116

**Comment by HinTak** [comment]
SkFilterQuality was removed June 2021, a bit under 3 years ago, in m94 : https://github.com/google/skia/commit/aebe248575affab2137f3d3fb9f94b8e397c4986

Anyway, the migration guide from FilterQuality to SamplingOptions is in: 
https://github.com/kyamagu/skia-python/issues/240

**Comment by HinTak** [comment]
To be pedantic, it is actually 4 settings - high, medium, low and none. None is even lower than low, as far as I see, but it is the default (instead of medium, which one might assume is the case).

**Comment by pavpanchekha** [comment]
Hi @HinTak, apologies for the long delay—the semester just ended so it's been hectic. I'm working on getting `skia-python` compiled from source and I'll first work on filing bugs for all of our uses of old APIs. Then I'll work on converting them to tests.

**Comment by pavpanchekha** [comment]
I can confirm that, on m124, our browser test suite passes without issue. However, actually running the browser doesn't work due to (maybe?) https://github.com/kyamagu/skia-python/issues/241, because all the text disappears due to the font metrics all returning zero:

<img width="912" alt="image" src="https://github.com/browserengineering/book/assets/30707/dae474ff-8269-4b76-8a3a-158775d41644">

**Comment by HinTak** [comment]
@pavpanchekha yes, you are on mac os? I tried "Times" and it doesn't work either (reset the push after the failed try). If you can see what incantation that gives a usable font on mac os, that would be nice.

**Comment by pavpanchekha** [comment]
Ok, I found the issue: https://github.com/HinTak/skia-python/pull/1

With this fix, I can successfully run the browser and it looks bit-for-bit identical to 87.5:

<img width="912" alt="Screenshot 2024-04-29 at 8 53 16 PM" src="https://github.com/browserengineering/book/assets/30707/e9d25201-1824-4829-88dd-5b64f2d4dee4">

I'm going to test images with `SamplingOptions` and then think about what remains to do on this.

**Comment by HinTak** [comment]
@pavpanchekha brilliant! That code is a bit confusing - how could it returns 5 zeros instead of none... I'll add that to the m124 pile now.

**Comment by pavpanchekha** [comment]
Closing this since we have now pinned the Skia version.
