### ISSUE TITLE
Typo or my misunderstanding ?

### ISSUE THREAD

**Issue by bunhere** [browserengineering/book#1269]
Hi, I am ryuan choi, a korean reader in this great articles.
As a engineer in the browser project, I hope that there would be a book about the browser internal.
 
Anyway, while I am reading this, I have some confusion that looks have some typos.
But I am afraid that I might misunderstand because of my poor english.
And I am not sure this is right place to report them.
Could let me know If I am wrong or this is not good place to report typos?

https://github.com/browserengineering/book/blob/65ed2c5b7578688cf81cd1c1f900db80bb33f236/book/text.md?plain=1#L798-L808

In my understanding,

Layout's fields that `flush` must update are `cursor_x`, `cursor_y`, and `line`.
I thought that `y` in 799 also looks be `cursor_y`.
Am I right?

**Comment by pavpanchekha** [comment]
This is a fine place to report a typo, yeah, you are right, on line 799 it should be `cursor_y`.
