### ISSUE TITLE
Blog post link paths need fixing

### ISSUE THREAD

**Issue by metamas** [browserengineering/book#218]
Hi, Pavel and Chris.

Thank you for creating this book!

Heads-up, when navigating to the website [blog posts](https://browser.engineering/blog/) via page links, they all 404 because "/blog" occurs twice in the path (e.g. [browser.engineering/blog/blog/why-python.html](https://browser.engineering/blog/blog/why-python.html)). Otherwise, those pages load fine after removing one of those "/blog" occurrences.

**Comment by chrishtr** [comment]
Thanks for the bug report! Fixing now.
