### ISSUE TITLE
Chapter 10: can't write to the guestbook after adding the SameSite check

### ISSUE THREAD

**Issue by shuhei** [browserengineering/book#409]
After adding the `SameSite` cookie check to the toy browser, I can't write messages on the guestbook server running locally, for example `http://localhost:8000`. I was able to reproduce the issue also with `src/server10.py` and `src/lab10.py` in this repository.

In the following code, `host` doesn't contain a port number while `top_level_host` does when both `url` and `top_level_url` are `http://localhost:8000/`. As a result, `allow_cookie` gets `False` for POST requests.

```py
def request(url, top_level_url, payload=None):
    # ...
    if host in COOKIE_JAR:
        cookie, params = COOKIE_JAR[host]
        allow_cookie = True
        if top_level_url and params.get("samesite", "none") == "lax":
            _, _, top_level_host, _ = top_level_url.split("/", 3)
            allow_cookie = (host == top_level_host or method == "GET")
```

**Comment by pavpanchekha** [comment]
This is a great catch, and must have been a frustrating bug to debug!

**Comment by pavpanchekha** [comment]
@chrishtr let's discuss what exactly we want to do here: do we want to implement the current standard (schemeful same-site), the old standard (strip off port number from `top_level_url`), use `url_origin` (too strict but at least code is simple), or something else.
