### ISSUE TITLE
How does the typo editing tool work?

### ISSUE THREAD

**Issue by SUPERCILEX** [browserengineering/book#462]
It doesn't seem to do anything as far as I can tell.

**Comment by chrishtr** [comment]
What do you mean by "doesn't seem to do anything"? Were you expecting the typo tool to apply to the webpage after submitting a typo?

**Comment by SUPERCILEX** [comment]
Nevermind, now it's working. I don't know what changed lol. When I had tried submitting the typo through the tool, no network requests were made. Now I can see some post requests.
