### ISSUE TITLE
Offline Use

### ISSUE THREAD

**Issue by Ibinola** [browserengineering/book#524]
Can this book be read offline?

**Comment by chrishtr** [comment]
> Can this book be read offline?

We don't have any direct support for it at the moment (e.g. we don't have a `ServiceWorker` on the site). But it should be easy to just download each chapter via your browser and read it that way.

**Comment by pavpanchekha** [comment]
You can also download the source code and build a local copy of the book with `make book`.

**Comment by nishantvarma** [comment]
I am getting an error like this while trying to `make book`:

```
pandoc --from markdown --to html --lua-filter=infra/filter.lua --fail-if-warnings --metadata-file=config.json  --toc --metadata=mode:book --template infra/template.html -c book.css book/intro.md -o www/intro.html
Error running filter infra/filter.lua:
infra/filter.lua:163: attempt to call a nil value (field 'List')
stack traceback:
	infra/filter.lua:163: in main chunk
make: *** [Makefile:66: www/intro.html] Error 
```

Does it have anything to do with Pandoc?
