### ISSUE TITLE
Dead links in Ch. 13

### ISSUE THREAD

**Issue by codyd51** [browserengineering/book#607]
Hi! Just a heads up that [these links](https://github.com/browserengineering/book/blob/main/book/animations.md?plain=1#L148-L149) in Chapter 13 point to `localhost`, and fail on the live site:

```
[eventloop-ch2]: http://localhost:8001/graphics.html#creating-windows
[eventloop-ch12]: http://localhost:8001/scheduling.html#animating-frames
```

I am not sure if there's a rendering step which is supposed to strip `localhost` links and tranform them to the deployed site's URL, or if this was just a mistake in prose? 

All the best, and thanks for the wonderful content.

**Comment by pavpanchekha** [comment]
Great catch. There isn't a rendering step, but perhaps we should write one.
