### ISSUE TITLE
Should Chapter 10 print out JS output in browser.load()?

### ISSUE THREAD

**Issue by BenjaminYe36** [browserengineering/book#831]
Hi! First of all, thanks for creating this amazing textbook.

I'm one of the TAs for the browser engineering course at UW that is based on this book this quarter, and our class found this expected `Script returned: None` but got nothing issue when running chapter 10 tests.

From our understanding of chapter 9 of the textbook, this line of code `print("Script returned: ", dukpy.evaljs(body))` is only intended to test the JS running for the first time and shouldn't be kept in the final product. Also, as shown later in chapter 9 textbook, the printing out line of code is replaced by `self.js.run(body)` (https://github.com/browserengineering/book/blob/main/book/scripts.md#handling-crashes).

If our understanding is correct, could you update the chapter 10 lab code and chapter 10 test accordingly? Thanks a lot!
We've updated our test files on our GitLab.
Also, the later lab code might also have this line of code.

**Comment by pavpanchekha** [comment]
Hi Benjamin, thanks for the bug report. Something got lost when editing Chapter 9. Will fix.
